<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "template_editor"
 *
 * Auto generated by Extension Builder 2017-05-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Template Editor',
	'description' => '',
	'category' => 'module',
	'author' => 'Aaron Enders',
	'author_email' => 'mail@aaron-enders.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);